require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/menu_groups", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # MenuGroup. As you add validations to MenuGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:menu_group)
  }

  let(:invalid_attributes) {
    attributes_for(:menu_group, name: nil)
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # MenuGroupsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      MenuGroup.create! valid_attributes
      get menu_groups_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      menu_group = MenuGroup.create! valid_attributes
      get menu_group_url(menu_group), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MenuGroup" do
        expect {
          post menu_groups_url,
               params: { menu_group: valid_attributes }, headers: valid_headers, as: :json
        }.to change(MenuGroup, :count).by(1)
      end

      it "renders a JSON response with the new menu_group" do
        post menu_groups_url,
             params: { menu_group: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MenuGroup" do
        expect {
          post menu_groups_url,
               params: { menu_group: invalid_attributes }, as: :json
        }.to change(MenuGroup, :count).by(0)
      end

      it "renders a JSON response with errors for the new menu_group" do
        post menu_groups_url,
             params: { menu_group: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "new group"
        }
      }

      it "updates the requested menu_group" do
        menu_group = MenuGroup.create! valid_attributes
        patch menu_group_url(menu_group),
              params: { menu_group: new_attributes }, headers: valid_headers, as: :json
        menu_group.reload

        expect(menu_group.name).to eq(new_attributes[:name])
      end

      it "renders a JSON response with the menu_group" do
        menu_group = MenuGroup.create! valid_attributes
        patch menu_group_url(menu_group),
              params: { menu_group: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the menu_group" do
        menu_group = MenuGroup.create! valid_attributes
        patch menu_group_url(menu_group),
              params: { menu_group: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested menu_group" do
      menu_group = MenuGroup.create! valid_attributes
      expect {
        delete menu_group_url(menu_group), headers: valid_headers, as: :json
      }.to change(MenuGroup, :count).by(-1)
    end
  end
end
